### ISSUE TITLE
Gumbel Minimum MSM

### ISSUE THREAD

**Issue by NikoAak** [dnvgl/qats#107]
**Is your feature request related to a problem? Please describe.**
I am doing a minimum gumbel distribution of several seeds. I use the fit function with the minimum value of each seed, and msm to do this. It seems the msm function returns the maximum msm parameters, while I would like the minimum msm parameters. 
For function msm(x) inside gumbel.py , is it possible to add a parameter that returns the mode of negative values (mean+e*b), instead of positive values (mean-e*b)? 

**Describe the solution you'd like**
Could for example add a "is_minima" to the function, or a boolean that evalute the x.mean value that automatically selects the apporiate mode.

**Comment by eneelo** [comment]
Hi,

Thanks for your suggestion. Just to be sure: you are referring to `gumbel.py`, and not the module `gumbelmin.py`? The latter is for Gumbel minima distribution, and although we realize that this module is somewhat unpolished yet it might perhaps provide what you are asking for?

Alternatively, if you prefer using the extreme maximum distribution in `gumbel.py`, you might consider treating it is a maxima distribution for the negative signal (i.e., multiply by minus one before and after using the Gumbel functions). 
And please clarify if I misunderstood your request.

**Comment by NikoAak** [comment]
Hi,

The gumbelmin.py actually covers my request. I unfortunately did not pick that up earlier, thanks for the quick reply.

Br
Nikolai
