### ISSUE TITLE
New project setup, build and release workflow

### ISSUE THREAD

**Issue by eneelo** [dnvgl/qats#114]
## Background 

The current release workflow is roughly as follows:

1. Merge relevant PRs into master branch.
2. Update CHANGELOG manually.
3. Assign new version by using ``version_bumper.py``, which sets a new git tag according to specified release type (major, minor or micro).
4. Push new git tag to directly onto master branch. This triggers the publish workflow ([.github/workflows/publish.yml](https://github.com/dnvgl/qats/blob/master/.github/workflows/publish.yml)), which uses Twine build and upload a new release to PyPi.
5. Project setup is handled by [setup.py](https://github.com/dnvgl/qats/blob/master/setup.py) and the version is extracted from the git tag by using [setuptools_scm](https://github.com/pypa/setuptools_scm).

However, the use of ``setup.py`` for project configuration is deprecated and not advised for new projects (see e.g. the note on using setup.py at [the end of this section on setuptools.pypa.io](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), [this note on setuptools.pypa.io](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setup-py) and [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) ). 

Following [PEP 518](https://peps.python.org/pep-0518/) and [PEP 621](https://peps.python.org/pep-0621/), the new standard way of doing it is by ``pyproject.toml``. A basic introduction is given on https://setuptools.pypa.io/en/latest/userguide/quickstart.html. Various ways of handling dynamic versioning are then available, although no one single solution seems to dominate as far as I can see. Possible options in the project configuration as well as build and release workflow are described below.

### Option 1 : keep current
**Pros:** 

- It has worked well so far.

**Cons:** 

- Further use of setup.py (invoked directly) is highly discouraged by smarter people.
- Updating the config and workflow should allow for easier implementation of future functionality. 
- A slightly more automated or assisted process (less manual steps) would be welcome. 

### Option 2: use pyproject.toml, keep setuptools_scm

It seems possible to replace ``setup.py`` by ``pyproject.toml`` while keeping ``setuptools_scm`` as the handler for dynamic versioning. See the setuptools_scm README file: https://github.com/pypa/setuptools_scm#setuptools_scm. 

**Pros:** 

- We avoid using the deprecated ``setup.py``. 
- We may still use git tags to assign a new version and initiate a new release.

**Cons:**

- The workflow is still largely the same as that described above, including manual steps.

### Option 3: implement "Release Please"

A third and interesting option is to implement the **Release Please** (https://github.com/googleapis/release-please) package and associated github action. According to its README file, _"Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps for your projects."_ (using ``pyproject.toml`` for project configuration).

An example of a project using Release Please is [equinor/tagreader-python](https://github.com/equinor/tagreader-python) (although with Poetry instead of Twine, but that shouldn't make too big a difference).

This seems to be a very interesting option.

**Pros:** 

- Setup is based on ``pyproject.toml``, avoiding ``setup.py``.
- Automates workflow to a larger degree by generation of changelog and handling version bumps.

**Cons:**

- Anticipate more work to get it up and running.

## Summary

- ``pyproject.toml`` is now the recommended way of configuring the python project (replacing the use of ``setup.py``).
- A good quickstart guide for using ``pyproject.toml`` is provided at https://setuptools.pypa.io/en/latest/userguide/quickstart.html.
- The ``setuptools_csm`` GitHub page provide a brief but good description of using ``setuptools_scm`` for dynamic versioning with ``pyproject.toml``. See https://github.com/pypa/setuptools_scm#setuptools_scm.
- Continued use of ``setuptools_scm`` (using git tags to assign package version) gives the least change to the existing build and release workflow.
- A more comprehensive option is to implement the Release Please package (and associated GitHub action), hosted and described at https://github.com/googleapis/release-please. Key points then are:
   * Release Please replaces ``setuptools_scm`` for version handling.
   * Instead of extracting the version from git tags, Release Please assigns/updates the version in ``pyproject.toml`` during the release process and at the same time assigns a git tag with this version (so simply put, reversed order compared to ``setuptools_scm``).
   * In addition, Release Please is designed to also handle updates of CHANGELOG.md.
- An example of a project using Release Please is found at [equinor/tagreader-python](https://github.com/equinor/tagreader-python).

## Conclusion 

**Option 2.**

Release Please (option 3) will be re-considered at a later stage if necessary.

## Tasks

- [x] Any other options not listed that above that can handle project configuration by ``pyproject.toml`` and dynamic versions (possibly but not necessarily by using git tags)?
- [x] Conclude on which option to go for.

Depending on the option selected:

- Update config and release workflow.
- Update README file (relevant sections).
- Test it as far possible, first manually then with the github actions (incl. release).

**Note:** Tasks to be completed are now handled in PR #115.

**Comment by tovop** [comment]
I have used `pyproject.toml` for project configuration the last years, first with Twine and later (still) with Poetry. I do agree with your argumentation, it is without doubt the right way to go. But, as you point out it has had and still have a weak spot when it comes to handling dynamic versioning and the release process. I was not aware of Release Please (I will come back to that) but I have tried several other options including the ones you mention. Briefly put I found other options just as inconvenient and ugly as the original. So I concluded to keep the versioning and release process manual and lean more on the release and tagging functionality in GitHub until methods have matured and converged.

And maybe it is sufficiently mature now? I will have to look more into it but Release Please looks promising. I will study it and screen for alternatives also. I'm ready to put in the work.
