### ISSUE TITLE
GUI import error

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#119]
**Describe the bug**
Pressing "Import from file" in the GUI causes error

**To Reproduce**
1. In GUI
2. Go to File
3. Click on "Import from File"

**Expected behavior**
Import dialogue opens

**Screenshots**
![image](https://github.com/dnvgl/qats/assets/44435680/dfb0dc25-3d8c-450c-9d73-1e3dc5143306)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Python: [3.10.11]
 - QATS Version [0.0.0] Dynamic versioning does not work as intended

**Additional context**
PySide6 causes the error:

> ValueError: <PySide6.QtWidgets.QFileDialog(0x2408de302e0) at 0x00000240974AF480> is not a valid QFileDialog.Option
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ebg.SEVAN\Code\qats\qats\app\gui.py", line 802, in on_import
>     options = dlg.Options()
>   File "C:\Users\ebg.SEVAN\Code\poetry_venv\qats-eJ8se3lo-py3.10\lib\site-packages\qtpy\QtWidgets.py", line 163, in <lambda>
>     QFileDialog.Options = lambda value=0: QFileDialog.Option(value)
>   File "C:\Python3\3.10.11\lib\enum.py", line 385, in __call__
>     return cls.__new__(cls, value)
>   File "C:\Python3\3.10.11\lib\enum.py", line 718, in __new__
>     raise exc
>   File "C:\Python3\3.10.11\lib\enum.py", line 700, in __new__
>     result = cls._missing_(value)
>   File "C:\Python3\3.10.11\lib\enum.py", line 844, in _missing_
>     if value < 0:
> TypeError: '<' not supported between instances of 'PySide6.QtWidgets.QFileDialog' and 'int'

**Comment by EBGlom** [comment]
1. Today, and it still is the latest from the Master branch.
2. Yes, I was on Python 3.7 before today

**Comment by EBGlom** [comment]
poetry install

**Comment by eneelo** [comment]
And you have installed the poetry-dynamic-version-plugin as described in [README.md](https://github.com/dnvgl/qats/blob/v5.0.6/README.md)?

`poetry self add "poetry-dynamic-versioning[plugin]"`

**Comment by eneelo** [comment]
By the way, how did you extract the qats version? 
Long story short; `qats --version`` (or in an interactive python session: `qats.__version__`) will currently always return the string "0.0.0" when in an editable install (e.g., from `poetry install`). This is due to how the dynamic versioning plugin works. On the other hand; if installed from a built distribution (e.g., from PyPi), it should always return the expected version string.

Also, the Help > About dialogue should show the correct version string, even when in an editable install. Alternatively, if dynamic versioning plugin works, the following python code should render the correct version string:

```python
>>> from importlib import metadata
>>> print(metadata.version("qats"))
```

**Comment by eneelo** [comment]
> But all of this is without poetry-dynamic-versioning

The metadata.version("qats") will only work if poetry-dynamic-versioning is installed at the time when `poetry install` is executed

**Comment by eneelo** [comment]
@EBGlom PR #121 fixes a proper version string, even after `poetry install`. Provided that the dynamic versioning plugin is properly installed, that is. Will be merged to master very soon.

**Comment by EBGlom** [comment]
Just a final update: It took until now to re-install poetry and PyCharm(!) to get poetry working in PyCharm again. Maybe the readme should be update with a warning to ensure that poetry is up to date before installing the dynamic versioning plugin.

With the plugin, the version is no longer 0.0.0, btw.
