### ISSUE TITLE
Pandas pickle dump format

### ISSUE THREAD

**Issue by mariustk** [dnvgl/qats#123]
For multiple reasons a pandas dataframe might be stored in pickle format. This format have advantages in speed and size compared with csv and json. However it is not directly supported by qats, typically we have patched a qats installation with a pickle reader, however it is not optimal to do this every time a new release of qats is published. 

An additional pandas pickle format to load pandas pickle dumps.

I can push a commit if I am added as contributor.

**Comment by mariustk** [comment]
![image](https://github.com/dnvgl/qats/assets/44461555/7ca05737-1628-4479-9b30-1ebddb35dcfd)

**Comment by eneelo** [comment]
Hi, this looks interesting! I will add you as a contributor so that you can push a branch and create a pull request. (Unless you have forked it? Then I would expect that you might be allowed to create a pull request from the fork).

**Comment by tovop** [comment]
Hi @mariustk 😀 This is very welcome. Indeed a handy format. Please add tests and example(s) too.

**Comment by mariustk** [comment]
It seems like forking it allowed me to create a pull request! @eneelo 
https://github.com/dnvgl/qats/pull/124
