### ISSUE TITLE
Add "remove mean" to apply frequency filters areas

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#16]
It is often desirable to remove the mean from signals, especially when looking at the signal spectrum. A tick-box would be good!

**Comment by EBGlom** [comment]
A few more ideas (put them here to not swamp the issues list):

- Power spectra smoothing
- Power spectra normalisation (e.g. to stdv = 1, in order to compare time series of different scale)
- RAO calculation, where one time series is selected as reference and the minimum coherence is input
- Probability cut-off for maxima/minima CDF fitting (to enable tail-fitting)

**Comment by tovop** [comment]
Thanks, valuable feedback.

The spectra displayed in the GUI today are smoothed. To simplify the GUI we have chosen a certain "amount of smoothing" balancing readability and distortion/frequency shift for general cases. With `qats.signal.psd` you can adjust the smoothing using the `nperseg` parameter. I will consider to create a settings feature to enable users to adjust the settings.

I will look into a "remove mean" tick box or a detrend radiobutton. You know, you can remove the mean by low-passing the signals at low frequency, say 0.01Hz.

Psd normalisation is a good idea. I will look at it. Again, you can do it already using the library (not the GUI).

I will look into the rao feature. I think that one will be prioritised over the other items on the wishlist.

You can do tail fitting using the library, but maybe we can add this to the abovementioned settings feature.

**Comment by tovop** [comment]
I had another look at the code, the signals are detrended (remove mean) before calculating spectral density.

I will close this issue and create new issues on the other features requests.

**Comment by EBGlom** [comment]
Some evidence that the time series are not 100% de-trended when generating the power spectra:

The difference between the signals is static -27.

![image](https://user-images.githubusercontent.com/44435680/68071987-b8d32f80-fd80-11e9-8d90-20ade09fb9bb.png)
