### ISSUE TITLE
GUI keyboard shortcuts

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#18]
Maybe Ctrl+C should be used for copying text only?

**Comment by eneelo** [comment]
By 'debugger', I assume you mean the logging window in the lower left frame. 
We could definitely rethink the use of `Ctrl + C`, however; is copying text from the logger such a frequent operation that it requires one of the "best" hotkeys? There is already the option to right-click in logger window for copying selected text.

Suggestion for re-assignment of hotkeys:

- `Ctrl + C`: copy plot/figure to clipboard as image.
- `Ctrl + Alt + C`: clear all time series.
- `Ctrl + Shift + C`: copy (selected?) text in logger frame.

 @EBGlom, @tovop: Any thoughts?

**Comment by EBGlom** [comment]
Yes, it's the logging window. 
I don't think we need to do this often, but after marking the text it was natural for me to use `Ctrl + C`.

Could `Ctrl + C` copy the figure by default, and copy text when text is selected?
Might be more complicated to implement, though.
`Ctrl + Shift + C` for text works fine too

How about `Ctrl + Del` for clearing all time series. 
Perhaps the clearing should should require a confirmation?
Pressing `Ctrl + Del` (or what we end up with) a second time can be used to give the confirmation.

**Comment by tovop** [comment]
Good suggestions guys. I definitely agree that ctrl + c should not be associated with clearing the db. I prefer ctrl + c for copying plot and ctrl + del for clearing the db. And no confirmation dialogue since ctrl + del isn't something you accidentally press.

When it comes to copying the logger text I am not sure how easy it is to assign hot keys for that (from a programming perspective). Anyway, right click and copy works.

**Comment by eneelo** [comment]
I agree. To summarize concluded updates:

- `Ctrl + C` to be re-assigned to copy plot.
- `Ctrl + Del` to be assigned to clear all loaded databases/time series.

Keyboard shortcut for copying logger text is not implement at present, unless we stumble across a code snippet that does the work.

**Comment by tovop** [comment]
I've changed the hotkey and will work out a solution for copying the figure to clipboard using `Ctrl + C`. It requires some fundamental changes to how the figures, canvases, widgets and app are sewn together.

Let's keep this issue open.
