### ISSUE TITLE
Harmonize readers

### ISSUE THREAD

**Issue by eneelo** [dnvgl/qats#2]
All readers to return double-dict {key : {name: ‘…’, time:[…] , data:[…], unit:’…’}}

**Comment by tovop** [comment]
I have to fresh up my memory on this one. Currently a reader is made up of one function parsing the key-file and one function parsing the file data file. Sometimes both the time series name and data is parsed from the same file e.g. ASCII and H5. The data reader is input only the index of the requested time series.

So to have the requested functionality we actually have to combine the two (key-reader and data-reader) in some way. Here there are many options. Anyway I think we would still like to keep the functionality to read only the keys to populate the time-series register without keeping the time-series data in memory.

What do you think?
* A single reader per format parsing both keys and data and with a boolean to toggle on/off reading the data?
* A separate key reader (returning a list of keys) and a separate data-reader which makes a second pass to the key reader to map the key to index relation?

**Comment by tovop** [comment]
Agreed to keep the existing return types out of consideration for efficiency and flexibility (we must be able to parse time-series names separately from the time series data).
