### ISSUE TITLE
TimeSeries and TsDB: plot methods improvements

### ISSUE THREAD

**Issue by eneelo** [dnvgl/qats#55]
Suggestions to improve plot methods of `TimeSeries` and `TsDB` classes.

`plot()` and `plot_psd()`:

- Introduce optional parameter `num`, to control `matplotlib.pyplot` figure number. Presently, figure number is hard-typed to 1, causing undesired behavior in cases when other plots have already been initiated but not yet shown/cleared. This parameter would then allow user to override the default figure number (which should still be 1, to avoid memory issues if a large number of time series are plotted using these methods).
- Introduce optional parameter `show` (bool), to control whether `pyplot.show()` is invoked or not. Default behavior should be same as today: show figure if `figurename` is not specified, do not show if `figurename` is specified.

`plot_cycle_range()`:
- Introduce optional parameter `bw` to control bar width. This parameter should be interpreted as a ratio of the bin width, such that bar width is calculated as `bw * dr` where `dr = r[1] - r[0]`. In many cases, the possibility to specify a smaller bar width (e.g. `bw=0.5`) may improve the readability of the barplot. Default should be 1.0 (same as today).

Example of `plot_cycle_range()` with `bw=0.5`:
![image](https://user-images.githubusercontent.com/45939678/67931467-2be27780-fbc2-11e9-889d-8f330edcfa98.png)

@tovop: Your views on the suggestions above would be appreciated.

**Comment by tovop** [comment]
I agree that this is an improvement. I think `bw` is OK.
