### ISSUE TITLE
Implement Matlab .mat v7.3 reader

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#57]
Implement a .mat v7.3 reader

I have made a crude .mat v7.3 reader using `hdf5storage` based on files received from Sintef Ocean as part of testing in the ocean basin: https://github.com/dnvgl/qats/tree/feature/matlab_v7.3_reader. Some items to consider based on what I have done:

- As per Matlab 2018a (yes, I should update) v7.3 files are not standard export format. I suggest that the original matlab reader is put in matlab_v7.2.py (as done in the branch) while the new reader is put in matlab_v7.3.py (an easy refactor of matlab.py in that branch). 
- As Matlab files can have any format, both Matlab reader needs to accept different formats. The original reader accepts a set of varable with the same length as a time vector. The v7.3 reader takes a list of channel names and a data variable which is (length of time series , number of channels + time) size. 
- Is there any good way to omit the double import (names and then data). For large files this slows thing down

**Comment by tovop** [comment]
Just a note for later. `hdf5storage.loadmat()` defaults to `scipy.io.loadmat()` for mat files v.7.2 and earlier. So it is possible to have a single reader and handle the variations in hierarchy under there.

**Comment by eneelo** [comment]
> Just a note for later. `hdf5storage.loadmat()` defaults to `scipy.io.loadmat()` for mat files v.7.2 and earlier. So it is possible to have a single reader and handle the variations in hierarchy under there.

Backwards compatibility is preferrable for this implementation. I think a common reader for v7.3 and v7.2 formats (+earlier) is a good way to do it, especially in light of what you point out above. If not feasible, for some yet unknown reason, we should still consider to keep the current module and function names for the v7.2 reader.

**Comment by EBGlom** [comment]
I support the use of one reader. But I'm not convinced that `hdf5storage` is the way to go. It is one and a half year since it was updated last.

**Comment by tovop** [comment]
Resolved with #62 .
