### ISSUE TITLE
Issues with the statistical table

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#58]
Nice feature, some issues though:

- [x] The sequence of numbers does not match the sequence of headings
- [x] The table doesn't clear when Ctrl+Del is pressed
- [x] The table doesn't update at all when Weibull fitting on one of the selected time series fails
- [x] The other statistical values should by presented even if the Weibull fitting fails. The P .XX could just display NaN

**Comment by eneelo** [comment]
These issues will be addressed in PR #59.
And I agree, presenting nan when fitting fails could be a proper way to do it.
