### ISSUE TITLE
GUI ideas

### ISSUE THREAD

**Issue by TordBT** [dnvgl/qats#60]
- Would like a way to clear the logger

- Would like to have the relevant file name displayed

Best Regards BNQU (Brand New Qats User)

**Comment by tovop** [comment]
@TordBT, is `Ctrl+Shift+Del` an OK hotkey for clearing the logger?

**Comment by tovop** [comment]
Hover over the time series in the list to see the time series' full path .

![image](https://user-images.githubusercontent.com/25904755/68230517-78321b00-fff9-11e9-800e-ade2d23738e2.png)
