### ISSUE TITLE
Compatibility with special characters

### ISSUE THREAD

**Issue by 3sigma** [dnvgl/qats#69]
Hello,

It would be great if you could add a compatibility with special characters.
For example, line 27 of qats/readers/csv.py would become:

`    df = pd.read_csv(path, nrows=1, sep=None, engine='python', encoding='utf-8')`

Thanks,
Nicolas

**Comment by eneelo** [comment]
Hi Nicolas, 

Thanks for the suggested improvement! Will look into this as soon as possible.
