### ISSUE TITLE
Column name lost when export only one item

### ISSUE THREAD

**Issue by 3sigma** [dnvgl/qats#70]
Hello,

When you export only one item in the app, the name of the second column in the exported file is "_" (the first one is the time).
It is OK when you export 2 items or more.

I am not sure it is a good solution, but replacing in tsdb.py line 784:

`container = self._make_export_friendly_names(container, keep_basename=basename)`

by:

```
        if len(container) == 1:
            container = self._make_export_friendly_names(container, keep_basename=True)
        else:
            container = self._make_export_friendly_names(container, keep_basename=basename)
```

solves the problem for what I want to do.

Thanks,
Nicoals

**Comment by eneelo** [comment]
Hi Nicolas, 
Thanks for the bug report, and suggested solution! Will have a look at this.

Regards,
Erling

**Comment by tovop** [comment]
Thank you @3sigma , you did most of the job by providing thorough breakdown of the problem. I think the referenced commit should fix it.

It will be released very soon.
