### ISSUE TITLE
Problem importing CSV files containing integers

### ISSUE THREAD

**Issue by 3sigma** [dnvgl/qats#71]
Hello,

Errors are generated when a CSV file has integer values. For example, this one:

"Temps (s)","X cons","Y cons"
2,-200,400
4,200,400
6,-50,350

Maybe line 569 of tsdb.py:

`
tslist[i] = TimeSeries(name, data[0, :], data[i + 1, :], parent=parent)
`

 could be replaced by something like:

`
tslist[i] = TimeSeries(name, data[0, :].astype(float), data[i + 1, :].astype(float), parent=parent)
`

At least, it solves the problem on my side.

Thanks,

Nicolas

**Comment by tovop** [comment]
@3sigma , I have now fixed it though at initiation of the `TimeSeries` object. I think the PR will be reviewed and merged anytime soon. Thanks again!
