### ISSUE TITLE
Fatal Error in Launcher

### ISSUE THREAD

**Issue by ArazPishdad** [dnvgl/qats#75]
Hello,

I have just installed the GUI. However I am getting an error called Fatal Error in Launcher! The error mentions Unable to Create Process.

It would be highly appreciated if you could possibly provide me with some advise on the issue.

Thanks very much in advance.

Best Regards

**Comment by eneelo** [comment]
Hi, 
We will advise if possible, however some more details would be needed to do so. 
At which stage did it fail? When trying to launch the GUI? What is the detailed error message?

**Comment by ArazPishdad** [comment]
Hi,

Thanks very much for your prompt response.

The error happens when I try to launch the GUI. Below is a snapshot of the error:

![QATS_GUI](https://user-images.githubusercontent.com/64986260/81400029-7bcf6780-912c-11ea-920a-8bf3bdc679c5.JPG)

**Comment by eneelo** [comment]
Hi, 
It puzzles me a bit, I haven't experienced this one before. This is somewhat a longshot, but I would suggest that you create a new, fresh conda environment and install qats there to see if it helps. Command line commands (with `py37qats` as the environment name):

1. `conda create -n py37qats python=3.7`
1. `conda activate py37qats`
1. `pyhon -m pip install qats` (basically the same as `pip install qats` but slightly more robust)
1. `python -m pip install pyqt5`
1. `qats app`

How does it look then?

**Comment by ArazPishdad** [comment]
Hi,

Thanks very much for your instructions, it's working now.

How could I use qats for fatigue analysis?

**Comment by eneelo** [comment]
> Hi,
> 
> Thanks very much for your instructions, it's working now.
> 
> How could I use qats for fatigue analysis?

That's good to hear. The fatigue calculation example should get you started on fatigue analysis:
https://qats.readthedocs.io/en/latest/examples.html#calculate-fatigue-damage-in-mooring-lines
