### ISSUE TITLE
Integration of time series

### ISSUE THREAD

**Issue by ogabrielsen** [dnvgl/qats#80]
From time to time I process time series of acceleration measurements. Accelerations can be integrated to obtain velocities and velocities can again be integrated to obtain displacements. I propose to implement a feature in qats for integration of the time series specifically for this type of use. For each integration it should also be possible to apply either a high-pass or a low-pass filter to the signal to remove numerical issues during integration. 

Say that acceleration data for a sensor is imported as signal S1, then it should be possible to define a new signal S2 which is the integration of S1, application of a high-pass filter and offset removed. See attached example.

[Processing of accelerations.pdf](https://github.com/dnvgl/qats/files/4804765/Processing.of.accelerations.pdf)

**Comment by eneelo** [comment]
As far as I can see, you are asking for functionality that is mostly available already. A fair approach could be for example:

1. Integrate the signal using `scipy.integrate` (as done in the example).
1. Filter the integrated time series using `qats.signal.highpass` [(link to docs)](https://qats.readthedocs.io/en/latest/api/qats/submodules.html#qats.signal.highpass), or initiate a `TimeSeries` instance and filter using the `TimeSeries.filter()` method [(link to docs)](https://qats.readthedocs.io/en/latest/api/qats/classes.html#qats.TimeSeries.filter).
1. Remove the mean of the filtered signal.

An idea could of course be to merge these steps into a single function, to obtain functionality somewhat similar to that implemented for numerical differentiation [(see `qats.motions`)](https://qats.readthedocs.io/en/latest/api/qats/submodules.html#module-qats.motions).

Please correct me if I have misunderstood.

**Comment by ogabrielsen** [comment]
I see that I missed one important point in my first entry: My suggestion is to include the proposed feature in the GUI. I understand that the library has functionality for doing so, but I liked the idea of being able to do operations on the time series from the GUI. However, the GUI is nice and clean as it is and perhaps it is best not to clutter it with more buttons - unless there could be a toggle that turns on advanced features which are normally hidden.

**Comment by eneelo** [comment]
> I see that I missed one important point in my first entry: My suggestion is to include the proposed feature in the GUI. 

Noted - that makes sense.

> However, the GUI is nice and clean as it is and perhaps it is best not to clutter it with more buttons - unless there could be a toggle that turns on advanced features which are normally hidden.

I agree, and that has been one of the main strategies; make simple and commonly used operations (time series plotting, filtering, spectrum, statistics) easily available and refer to the underlying library for more advanced operations. However, I like the idea so I think we should leave the issue open for now in case we decide to implement something along this line at a later stage.

**Comment by tovop** [comment]
Closing this. Can be reopened once we have a clearer idea on how to generically implement this in the GUI.
