### ISSUE TITLE
Number of decimals in time window fields

### ISSUE THREAD

**Issue by ogabrielsen** [dnvgl/qats#81]
I propose to make it possible to enter more decimals in the two fields for setting the time window. In the current version the number of decimals is limited to 2. I have some time series data with a very high sampling rate and need to specify the window in micro seconds (10E-6). One way to do this could be to control this under File --> Settings as two decimals is probably sufficient for most time series data.

**Comment by eneelo** [comment]
I agree with the proposed solution. We will look at including this in PR #79.
