### ISSUE TITLE
Reading riflex/simo, sima direct access name keys for Wind Turbine output

### ISSUE THREAD

**Issue by larsmr** [dnvgl/qats#83]
Riflex key file for wind turbine output is define different from for instance 'noddis', 'elmsfo', 'elmfor': 
- Issues occurs in _name_suffices routine in sima.py since witurb.bin does not includes DOFs
- Added a workaround in branch: sima_wind_name

**Comment by larsmr** [comment]
[swach_witurb.zip](https://github.com/dnvgl/qats/files/5536100/swach_witurb.zip)

**Comment by larsmr** [comment]
[key_swach_blresp.zip](https://github.com/dnvgl/qats/files/5536391/key_swach_blresp.zip)

**Comment by tovop** [comment]
We will look into this right away and solve it with #79 . Thank you for providing a solution and and example data files.
