### ISSUE TITLE
Qats does not work using python39

### ISSUE THREAD

**Issue by grobaar** [dnvgl/qats#86]
python39.

The  Qats interface closes if I try to display a time series in a h5-file.
No error message is produced

The h5-file is read using the python code.

**Comment by eneelo** [comment]
Additional info from quick testing:

- with python 3.8, h5-file is read without errors using (both when using the api and when using gui).
- with python 3.9, h5-file is correctly loaded when using the api. When using the gui, database is loaded but GUI closes when 'display' is invoked. No error message is generated.

The package is not currently tested for python >3.7, but we should consider including tests for py 3.8 and 3.9 if the bug may be easily fixed.

**Comment by tovop** [comment]
I installed it in a clean environment with Python `3.9.5` and PyQt5 `5.15.4`. Both GUI and API worked well with all file formats. I have not tested with Pyside, which Qt binding did you use @eneelo ?

**Comment by eneelo** [comment]
It seems that the Qt binding is indeed the cause. I used pyside 2 `5.15.2`. Confirm that the databased is loaded/displayed in the GUI if PyQt5 is used instead.

**Comment by tovop** [comment]
Solved. Use PyQt5 until Pyside2 supports Python 3.9. Testing with Python versions 3.7, 3.8 and 3.9 will be added ASAP.
