### ISSUE TITLE
Qats app

### ISSUE THREAD

**Issue by eigilaso** [dnvgl/qats#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by eigilaso** [comment]
Hi! I am using the qats app to plot data from SIMA. I can't seem to change the name of the curves in the plot, by the command 'edit axis, curve and image parameters. I am launching the app from the anaconda prompt, and get a following message when displaying the selected data from .h5 file. Does anyone have an idea what could be the issue? 


![error](https://user-images.githubusercontent.com/114750123/193286098-f9c80f26-4fde-40f6-b4b6-bcd1310e8c39.png)

**Comment by eneelo** [comment]
Hi,
1) If I understand you issue correctly, try enabling "(Re-)Generate automatic legend" on the Axes tab, then clik Apply. See screenshot below. Also, if this is an operation you need to do frequently, you could consider using a script to load the .h5 file(s), change the names of the time series, and write a new file for use with QATS. Whether this is a good approach depends on your use case.

![image](https://user-images.githubusercontent.com/45939678/193477449-1883de2e-d1f2-4633-92dd-eb01b590eb13.png)


2) The 'nperseg' warning is related to the calculation of the power spectrum. From the top of my head, I think it might be related to the length of the time series. Are your time series by any chance of limited duration?

Hope this helps you a bit on the way. If you want better answers, please provide more details.

**Comment by eigilaso** [comment]
Thank you! enabling the "(Re-)Generate automatic legend" worked well
